pdf_reader_task:
  description: >
    Read the pdf file and return the pdf and send to the translator agent
  expected_output: >
    The pdf from the pdf file
  agent: pdf_reader

translator_task:
  description: >
    Translate the pdf from the pdf file to the target language and send to the pdf writer agent
  expected_output: >
    The translated pdf
  agent: translator

pdf_writer_task:
  description: >
    Write the translated pdf to a new pdf file
  expected_output: >
    The translated pdf only in a pdf file
  agent: pdf_writer
